<?php

/**
 * BaseStranka
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $link_h1
 * @property string $title_seo
 * @property string $keywords
 * @property string $description
 * @property string $title_str
 * @property string $top_img
 * @property string $top_img_title
 * @property string $top_img_alt
 * @property clob $popis_levy
 * @property clob $popis_pravy
 * @property string $region
 * @property integer $vzdalenost
 * @property string $img1
 * @property string $img1_title
 * @property string $img1_alt
 * @property string $img2
 * @property string $img2_title
 * @property string $img2_alt
 * @property string $img3
 * @property string $img3_title
 * @property string $img3_alt
 * @property string $img4
 * @property string $img4_title
 * @property string $img4_alt
 * @property string $promo1_title
 * @property string $promo1_img
 * @property string $promo1_img_title
 * @property string $promo1_img_alt
 * @property integer $promo1_gallery_id
 * @property integer $promo1_star
 * @property clob $promo1_popis
 * @property string $promo1_cena
 * @property string $promo1_link
 * @property string $promo2_title
 * @property string $promo2_img
 * @property string $promo2_img_title
 * @property string $promo2_img_alt
 * @property integer $promo2_gallery_id
 * @property integer $promo2_star
 * @property clob $promo2_popis
 * @property string $promo2_cena
 * @property string $promo2_link
 * @property string $promo3_title
 * @property string $promo3_img
 * @property string $promo3_img_title
 * @property string $promo3_img_alt
 * @property integer $promo3_gallery_id
 * @property integer $promo3_star
 * @property clob $promo3_popis
 * @property string $promo3_cena
 * @property string $promo3_link
 * @property string $promo4_title
 * @property string $promo4_img
 * @property string $promo4_img_title
 * @property string $promo4_img_alt
 * @property integer $promo4_gallery_id
 * @property integer $promo4_star
 * @property clob $promo4_popis
 * @property string $promo4_cena
 * @property string $promo4_link
 * @property string $baner1_img
 * @property string $baner1_img_title
 * @property string $baner1_img_alt
 * @property string $baner1_link
 * @property string $baner2_img
 * @property string $baner2_img_title
 * @property string $baner2_img_alt
 * @property string $baner2_link
 * @property string $baner3_img
 * @property string $baner3_img_title
 * @property string $baner3_img_alt
 * @property string $baner3_link
 * @property Gallery $Gallery1
 * @property Gallery $Gallery2
 * @property Gallery $Gallery3
 * @property Gallery $Gallery4
 * 
 * @method integer getId()                Returns the current record's "id" value
 * @method string  getName()              Returns the current record's "name" value
 * @method string  getLinkH1()            Returns the current record's "link_h1" value
 * @method string  getTitleSeo()          Returns the current record's "title_seo" value
 * @method string  getKeywords()          Returns the current record's "keywords" value
 * @method string  getDescription()       Returns the current record's "description" value
 * @method string  getTitleStr()          Returns the current record's "title_str" value
 * @method string  getTopImg()            Returns the current record's "top_img" value
 * @method string  getTopImgTitle()       Returns the current record's "top_img_title" value
 * @method string  getTopImgAlt()         Returns the current record's "top_img_alt" value
 * @method clob    getPopisLevy()         Returns the current record's "popis_levy" value
 * @method clob    getPopisPravy()        Returns the current record's "popis_pravy" value
 * @method string  getRegion()            Returns the current record's "region" value
 * @method integer getVzdalenost()        Returns the current record's "vzdalenost" value
 * @method string  getImg1()              Returns the current record's "img1" value
 * @method string  getImg1Title()         Returns the current record's "img1_title" value
 * @method string  getImg1Alt()           Returns the current record's "img1_alt" value
 * @method string  getImg2()              Returns the current record's "img2" value
 * @method string  getImg2Title()         Returns the current record's "img2_title" value
 * @method string  getImg2Alt()           Returns the current record's "img2_alt" value
 * @method string  getImg3()              Returns the current record's "img3" value
 * @method string  getImg3Title()         Returns the current record's "img3_title" value
 * @method string  getImg3Alt()           Returns the current record's "img3_alt" value
 * @method string  getImg4()              Returns the current record's "img4" value
 * @method string  getImg4Title()         Returns the current record's "img4_title" value
 * @method string  getImg4Alt()           Returns the current record's "img4_alt" value
 * @method string  getPromo1Title()       Returns the current record's "promo1_title" value
 * @method string  getPromo1Img()         Returns the current record's "promo1_img" value
 * @method string  getPromo1ImgTitle()    Returns the current record's "promo1_img_title" value
 * @method string  getPromo1ImgAlt()      Returns the current record's "promo1_img_alt" value
 * @method integer getPromo1GalleryId()   Returns the current record's "promo1_gallery_id" value
 * @method integer getPromo1Star()        Returns the current record's "promo1_star" value
 * @method clob    getPromo1Popis()       Returns the current record's "promo1_popis" value
 * @method string  getPromo1Cena()        Returns the current record's "promo1_cena" value
 * @method string  getPromo1Link()        Returns the current record's "promo1_link" value
 * @method string  getPromo2Title()       Returns the current record's "promo2_title" value
 * @method string  getPromo2Img()         Returns the current record's "promo2_img" value
 * @method string  getPromo2ImgTitle()    Returns the current record's "promo2_img_title" value
 * @method string  getPromo2ImgAlt()      Returns the current record's "promo2_img_alt" value
 * @method integer getPromo2GalleryId()   Returns the current record's "promo2_gallery_id" value
 * @method integer getPromo2Star()        Returns the current record's "promo2_star" value
 * @method clob    getPromo2Popis()       Returns the current record's "promo2_popis" value
 * @method string  getPromo2Cena()        Returns the current record's "promo2_cena" value
 * @method string  getPromo2Link()        Returns the current record's "promo2_link" value
 * @method string  getPromo3Title()       Returns the current record's "promo3_title" value
 * @method string  getPromo3Img()         Returns the current record's "promo3_img" value
 * @method string  getPromo3ImgTitle()    Returns the current record's "promo3_img_title" value
 * @method string  getPromo3ImgAlt()      Returns the current record's "promo3_img_alt" value
 * @method integer getPromo3GalleryId()   Returns the current record's "promo3_gallery_id" value
 * @method integer getPromo3Star()        Returns the current record's "promo3_star" value
 * @method clob    getPromo3Popis()       Returns the current record's "promo3_popis" value
 * @method string  getPromo3Cena()        Returns the current record's "promo3_cena" value
 * @method string  getPromo3Link()        Returns the current record's "promo3_link" value
 * @method string  getPromo4Title()       Returns the current record's "promo4_title" value
 * @method string  getPromo4Img()         Returns the current record's "promo4_img" value
 * @method string  getPromo4ImgTitle()    Returns the current record's "promo4_img_title" value
 * @method string  getPromo4ImgAlt()      Returns the current record's "promo4_img_alt" value
 * @method integer getPromo4GalleryId()   Returns the current record's "promo4_gallery_id" value
 * @method integer getPromo4Star()        Returns the current record's "promo4_star" value
 * @method clob    getPromo4Popis()       Returns the current record's "promo4_popis" value
 * @method string  getPromo4Cena()        Returns the current record's "promo4_cena" value
 * @method string  getPromo4Link()        Returns the current record's "promo4_link" value
 * @method string  getBaner1Img()         Returns the current record's "baner1_img" value
 * @method string  getBaner1ImgTitle()    Returns the current record's "baner1_img_title" value
 * @method string  getBaner1ImgAlt()      Returns the current record's "baner1_img_alt" value
 * @method string  getBaner1Link()        Returns the current record's "baner1_link" value
 * @method string  getBaner2Img()         Returns the current record's "baner2_img" value
 * @method string  getBaner2ImgTitle()    Returns the current record's "baner2_img_title" value
 * @method string  getBaner2ImgAlt()      Returns the current record's "baner2_img_alt" value
 * @method string  getBaner2Link()        Returns the current record's "baner2_link" value
 * @method string  getBaner3Img()         Returns the current record's "baner3_img" value
 * @method string  getBaner3ImgTitle()    Returns the current record's "baner3_img_title" value
 * @method string  getBaner3ImgAlt()      Returns the current record's "baner3_img_alt" value
 * @method string  getBaner3Link()        Returns the current record's "baner3_link" value
 * @method Gallery getGallery1()          Returns the current record's "Gallery1" value
 * @method Gallery getGallery2()          Returns the current record's "Gallery2" value
 * @method Gallery getGallery3()          Returns the current record's "Gallery3" value
 * @method Gallery getGallery4()          Returns the current record's "Gallery4" value
 * @method Stranka setId()                Sets the current record's "id" value
 * @method Stranka setName()              Sets the current record's "name" value
 * @method Stranka setLinkH1()            Sets the current record's "link_h1" value
 * @method Stranka setTitleSeo()          Sets the current record's "title_seo" value
 * @method Stranka setKeywords()          Sets the current record's "keywords" value
 * @method Stranka setDescription()       Sets the current record's "description" value
 * @method Stranka setTitleStr()          Sets the current record's "title_str" value
 * @method Stranka setTopImg()            Sets the current record's "top_img" value
 * @method Stranka setTopImgTitle()       Sets the current record's "top_img_title" value
 * @method Stranka setTopImgAlt()         Sets the current record's "top_img_alt" value
 * @method Stranka setPopisLevy()         Sets the current record's "popis_levy" value
 * @method Stranka setPopisPravy()        Sets the current record's "popis_pravy" value
 * @method Stranka setRegion()            Sets the current record's "region" value
 * @method Stranka setVzdalenost()        Sets the current record's "vzdalenost" value
 * @method Stranka setImg1()              Sets the current record's "img1" value
 * @method Stranka setImg1Title()         Sets the current record's "img1_title" value
 * @method Stranka setImg1Alt()           Sets the current record's "img1_alt" value
 * @method Stranka setImg2()              Sets the current record's "img2" value
 * @method Stranka setImg2Title()         Sets the current record's "img2_title" value
 * @method Stranka setImg2Alt()           Sets the current record's "img2_alt" value
 * @method Stranka setImg3()              Sets the current record's "img3" value
 * @method Stranka setImg3Title()         Sets the current record's "img3_title" value
 * @method Stranka setImg3Alt()           Sets the current record's "img3_alt" value
 * @method Stranka setImg4()              Sets the current record's "img4" value
 * @method Stranka setImg4Title()         Sets the current record's "img4_title" value
 * @method Stranka setImg4Alt()           Sets the current record's "img4_alt" value
 * @method Stranka setPromo1Title()       Sets the current record's "promo1_title" value
 * @method Stranka setPromo1Img()         Sets the current record's "promo1_img" value
 * @method Stranka setPromo1ImgTitle()    Sets the current record's "promo1_img_title" value
 * @method Stranka setPromo1ImgAlt()      Sets the current record's "promo1_img_alt" value
 * @method Stranka setPromo1GalleryId()   Sets the current record's "promo1_gallery_id" value
 * @method Stranka setPromo1Star()        Sets the current record's "promo1_star" value
 * @method Stranka setPromo1Popis()       Sets the current record's "promo1_popis" value
 * @method Stranka setPromo1Cena()        Sets the current record's "promo1_cena" value
 * @method Stranka setPromo1Link()        Sets the current record's "promo1_link" value
 * @method Stranka setPromo2Title()       Sets the current record's "promo2_title" value
 * @method Stranka setPromo2Img()         Sets the current record's "promo2_img" value
 * @method Stranka setPromo2ImgTitle()    Sets the current record's "promo2_img_title" value
 * @method Stranka setPromo2ImgAlt()      Sets the current record's "promo2_img_alt" value
 * @method Stranka setPromo2GalleryId()   Sets the current record's "promo2_gallery_id" value
 * @method Stranka setPromo2Star()        Sets the current record's "promo2_star" value
 * @method Stranka setPromo2Popis()       Sets the current record's "promo2_popis" value
 * @method Stranka setPromo2Cena()        Sets the current record's "promo2_cena" value
 * @method Stranka setPromo2Link()        Sets the current record's "promo2_link" value
 * @method Stranka setPromo3Title()       Sets the current record's "promo3_title" value
 * @method Stranka setPromo3Img()         Sets the current record's "promo3_img" value
 * @method Stranka setPromo3ImgTitle()    Sets the current record's "promo3_img_title" value
 * @method Stranka setPromo3ImgAlt()      Sets the current record's "promo3_img_alt" value
 * @method Stranka setPromo3GalleryId()   Sets the current record's "promo3_gallery_id" value
 * @method Stranka setPromo3Star()        Sets the current record's "promo3_star" value
 * @method Stranka setPromo3Popis()       Sets the current record's "promo3_popis" value
 * @method Stranka setPromo3Cena()        Sets the current record's "promo3_cena" value
 * @method Stranka setPromo3Link()        Sets the current record's "promo3_link" value
 * @method Stranka setPromo4Title()       Sets the current record's "promo4_title" value
 * @method Stranka setPromo4Img()         Sets the current record's "promo4_img" value
 * @method Stranka setPromo4ImgTitle()    Sets the current record's "promo4_img_title" value
 * @method Stranka setPromo4ImgAlt()      Sets the current record's "promo4_img_alt" value
 * @method Stranka setPromo4GalleryId()   Sets the current record's "promo4_gallery_id" value
 * @method Stranka setPromo4Star()        Sets the current record's "promo4_star" value
 * @method Stranka setPromo4Popis()       Sets the current record's "promo4_popis" value
 * @method Stranka setPromo4Cena()        Sets the current record's "promo4_cena" value
 * @method Stranka setPromo4Link()        Sets the current record's "promo4_link" value
 * @method Stranka setBaner1Img()         Sets the current record's "baner1_img" value
 * @method Stranka setBaner1ImgTitle()    Sets the current record's "baner1_img_title" value
 * @method Stranka setBaner1ImgAlt()      Sets the current record's "baner1_img_alt" value
 * @method Stranka setBaner1Link()        Sets the current record's "baner1_link" value
 * @method Stranka setBaner2Img()         Sets the current record's "baner2_img" value
 * @method Stranka setBaner2ImgTitle()    Sets the current record's "baner2_img_title" value
 * @method Stranka setBaner2ImgAlt()      Sets the current record's "baner2_img_alt" value
 * @method Stranka setBaner2Link()        Sets the current record's "baner2_link" value
 * @method Stranka setBaner3Img()         Sets the current record's "baner3_img" value
 * @method Stranka setBaner3ImgTitle()    Sets the current record's "baner3_img_title" value
 * @method Stranka setBaner3ImgAlt()      Sets the current record's "baner3_img_alt" value
 * @method Stranka setBaner3Link()        Sets the current record's "baner3_link" value
 * @method Stranka setGallery1()          Sets the current record's "Gallery1" value
 * @method Stranka setGallery2()          Sets the current record's "Gallery2" value
 * @method Stranka setGallery3()          Sets the current record's "Gallery3" value
 * @method Stranka setGallery4()          Sets the current record's "Gallery4" value
 * 
 * @package    dunaverde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStranka extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stranka');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'default' => 'homepage',
             'length' => 50,
             ));
        $this->hasColumn('link_h1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_seo', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_str', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('top_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('top_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('top_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('popis_levy', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('popis_pravy', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('region', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('vzdalenost', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('img1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img1_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('img1_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('img2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img2_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('img2_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('img3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img3_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('img3_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('img4', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img4_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('img4_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('promo1_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo1_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo1_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('promo1_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('promo1_gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('promo1_star', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('promo1_popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('promo1_cena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo1_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo2_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo2_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo2_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('promo2_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('promo2_gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('promo2_star', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('promo2_popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('promo2_cena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo2_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo3_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo3_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo3_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('promo3_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('promo3_gallery_id', 'integer', 255, array(
             'type' => 'integer',
             'length' => 255,
             ));
        $this->hasColumn('promo3_star', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('promo3_popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('promo3_cena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo3_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo4_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo4_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo4_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('promo4_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('promo4_gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('promo4_star', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('promo4_popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('promo4_cena', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('promo4_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('baner1_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('baner1_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('baner1_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('baner1_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('baner2_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('baner2_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('baner2_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('baner2_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('baner3_img', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('baner3_img_title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('baner3_img_alt', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('baner3_link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery as Gallery1', array(
             'local' => 'promo1_gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Gallery as Gallery2', array(
             'local' => 'promo2_gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Gallery as Gallery3', array(
             'local' => 'promo3_gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Gallery as Gallery4', array(
             'local' => 'promo4_gallery_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}