<?php

/**
 * BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $SiteName
 * @property string $email
 * @property string $tel
 * @property string $mobil
 * @property clob $pracovni_doba
 * @property string $ulice
 * @property string $mesto
 * @property string $web_adr
 * @property string $ga_code
 * @property string $google_overeni
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method string  getSiteName()       Returns the current record's "SiteName" value
 * @method string  getEmail()          Returns the current record's "email" value
 * @method string  getTel()            Returns the current record's "tel" value
 * @method string  getMobil()          Returns the current record's "mobil" value
 * @method clob    getPracovniDoba()   Returns the current record's "pracovni_doba" value
 * @method string  getUlice()          Returns the current record's "ulice" value
 * @method string  getMesto()          Returns the current record's "mesto" value
 * @method string  getWebAdr()         Returns the current record's "web_adr" value
 * @method string  getGaCode()         Returns the current record's "ga_code" value
 * @method string  getGoogleOvereni()  Returns the current record's "google_overeni" value
 * @method Setting setId()             Sets the current record's "id" value
 * @method Setting setSiteName()       Sets the current record's "SiteName" value
 * @method Setting setEmail()          Sets the current record's "email" value
 * @method Setting setTel()            Sets the current record's "tel" value
 * @method Setting setMobil()          Sets the current record's "mobil" value
 * @method Setting setPracovniDoba()   Sets the current record's "pracovni_doba" value
 * @method Setting setUlice()          Sets the current record's "ulice" value
 * @method Setting setMesto()          Sets the current record's "mesto" value
 * @method Setting setWebAdr()         Sets the current record's "web_adr" value
 * @method Setting setGaCode()         Sets the current record's "ga_code" value
 * @method Setting setGoogleOvereni()  Sets the current record's "google_overeni" value
 * 
 * @package    dunaverde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('SiteName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mobil', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('pracovni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ulice', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('mesto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('web_adr', 'string', 55, array(
             'type' => 'string',
             'length' => 55,
             ));
        $this->hasColumn('ga_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('google_overeni', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}