<?php
// auto-generated by sfCacheConfigHandler
// date: 2012/01/27 10:57:19
$this->addCache($moduleName, 'index', array('withLayout' => true, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => true, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));

